ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    map_frame: map
    publish_tf: true
    tf_publish_period: 0.02

    odometry0: /odom
    odometry0_config: [true,  true,  false,
                       false, false, true,
                       true,  false,  false,
                       false, false, true,
                       false, false, false]

    imu0: /imu/data
    imu0_config: [false, false, false,   # x, y, z posição
                  false, false, true,    # roll, pitch, yaw orientação (ativar todos para orientação completa)
                  false, false, false,
                  false,  false,  false,    # roll, pitch, yaw velocidade angular
                  true, false, false]
    imu0_differential: true  # Fundamental para integração correta
