ekf_filter_node:
    ros__parameters:

        use_sim_time: true
        
        frequency: 30.0
        two_d_mode: true #true
        publish_tf: true

        map_frame: map
        odom_frame: odom
        base_link_frame: base_footprint
        world_frame: odom

        odom0: diff_cont/odom
        imu0: imu/data

        #        [x_pos   , y_pos    , z_pos,
        #         roll    , pitch    , yaw,
        #         x_vel   , y_vel    , z_vel,
        #         roll_vel, pitch_vel, yaw_vel,
        #         x_accel , y_accel  , z_accel]

        odom0_config: [false, false, false,
               false, false, false,
               true, true, false,     # velocidades x, y
               false, false, true,    # velocidade angular z
               false, false, false]


        imu0_config: [false, false, false,
                        false, false, true,    # roll, pitch, yaw
                        false, false, false,
                        false, false, true,    # angular velocities
                        false, false, false]   # linear accelerations
