controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster 

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_footprint

    left_wheel_names: ['roda_FE', 'roda_TE']
    right_wheel_names: ['roda_FD', 'roda_TD']
    
    wheel_separation: 0.17
    wheel_radius: 0.045

    pose_covariance_diagonal: [0.005, 0.005, 1e6, 1e6, 1e6, 0.05]
    twist_covariance_diagonal: [0.01, 0.01, 1e6, 1e6, 1e6, 0.1]

    use_stamped_vel: false

    enable_odom_tf: false

imu_broadcaster:
  ros__parameters:

    sensor_name: imu_sensor
    frame_id: imu
   
    static_covariance_orientation: [2.63882e-06, 0.0, 0.0, 0.0, 7.50018e-06, 0.0, 0.0, 0.0, 2.89257e-09]
    static_covariance_angular_velocity: [2.71413e-07, 0.0, 0.0, 0.0, 6.79488e-07, 0.0, 0.0, 0.0, 4.37879e-07]
    static_covariance_linear_acceleration: [0.00133755, 0.0, 0.0, 0.0, 0.000209753, 0.0, 0.0, 0.0, 0.00143276]