twist_mux:
  ros__parameters:
    use_stamped: true 
    
    topics:
      name: navigation
      topic: cmd_vel_nav
      timeout: 0.5
      priority: 100
      
      joystick:
        topic   : joy_vel
        timeout : 0.5
        priority: 100

        
    locks:
      name: e_stop
      topic: e_stop
      timeout: 0.0
      priority: 255