twist_mux:
  ros__parameters:
    use_stamped: true

    topics:
      nav2: 
        topic: cmd_vel_nav 
        timeout: 0.5
        priority: 200

      joystick:
        topic   : joy_vel 
        timeout : 0.2
        priority: 255

      teleop:
        topic: cmd_vel_teleop
        timeout: 0.5
        priority: 200

     

      
